# Generated by Django 3.2.9 on 2021-12-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('participantID', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VideoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('recordingSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awstranscription.recordingsession')),
            ],
        ),
        migrations.CreateModel(
            name='AudioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('recordingSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awstranscription.recordingsession')),
            ],
        ),
    ]
