# Generated by Django 3.2.9 on 2021-12-12 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=200)),
                ('participantID', models.CharField(max_length=200)),
                ('audioInput', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awstranscription.audioinput')),
                ('videoInput', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awstranscription.videoinput')),
            ],
        ),
    ]
