# Generated by Django 3.2.9 on 2021-12-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awstranscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoinput',
            old_name='filename',
            new_name='fileName',
        ),
    ]
