# Generated by Django 3.2.9 on 2021-12-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awstranscription', '0002_rename_projectname_recordingsession_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioinput',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videoinput',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
