# Generated by Django 3.2.9 on 2021-12-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awstranscription', '0003_auto_20211207_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='videoinput',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
