# Generated by Django 3.2.9 on 2021-12-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awstranscription', '0004_auto_20211207_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
