# Generated by Django 3.2.9 on 2021-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awstranscription', '0005_alter_audioinput_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
