# Generated by Django 3.2.9 on 2021-12-10 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awstranscription', '0006_alter_audioinput_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='recordingSession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awstranscription.recordingsession'),
        ),
        migrations.AlterField(
            model_name='videoinput',
            name='recordingSession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='awstranscription.recordingsession'),
        ),
    ]
