# Generated by Django 3.2 on 2022-01-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='recordingsession',
            name='Results',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.results'),
        ),
    ]
