# Generated by Django 3.2 on 2022-01-15 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0002_auto_20220115_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='media',
        ),
        migrations.RemoveField(
            model_name='results',
            name='recordedTime',
        ),
    ]
