# Generated by Django 3.2 on 2022-03-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0005_auto_20220306_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingsession',
            name='audioInput',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.audioinput'),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='audioWords',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.audiowords'),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='fitbit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.fitbit'),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='gPS',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.gps'),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='hRV',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.hrv'),
        ),
        migrations.AlterField(
            model_name='recordingsession',
            name='videoInput',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.videoinput'),
        ),
    ]
