# Generated by Django 3.2.9 on 2022-06-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0006_auto_20220307_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitbit',
            new_name='Empatica_EDA',
        ),
        migrations.RenameField(
            model_name='recordingsession',
            old_name='fitbit',
            new_name='empatica_EDA',
        ),
    ]
