# Generated by Django 3.2.9 on 2022-06-29 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataportal', '0009_auto_20220609_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawAudioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='RawVideoInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=200)),
                ('recordedTime', models.DateTimeField(verbose_name='date recorded')),
                ('media', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='RawProcessingResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=200)),
                ('rawAudioInput', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.rawaudioinput')),
                ('rawVideoInput', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.rawvideoinput')),
                ('results', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataportal.results')),
            ],
        ),
    ]
